name: tuplebd
version: 1.1.0
description: A library providing a tuple data structure.
repository: https://github.com/orlandobolivar896/tuplebd.dart

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  hive_test: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
